export const ACTIONS = {
	GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
	GET_POSTS_REQUEST: 'GET_POSTS_REQUEST',
	GET_POSTS_FAILURE: 'GET_POSTS_FAILURE',
	GET_USER_SUCCESS: 'GET_USER_SUCCESS',
	GET_USER_REQUEST: 'GET_USER_REQUEST',
	GET_USER_FAILURE: 'GET_USER_FAILURE',
};
