export const ACTIONS = {
	GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
	GET_POSTS_REQUEST: 'GET_POSTS_REQUEST',
	GET_POSTS_FAILURE: 'GET_POSTS_FAILURE',
	GET_ONE_POST_SUCCESS: 'GET_ONE_POST_SUCCESS',
	GET_ONE_POST_REQUEST: 'GET_ONE_POST_REQUEST',
	GET_ONE_POST_FAILURE: 'GET_ONE_POST_FAILURE',
};
