export const ACTIONS = {
  ADD_TODO: 'ADD_TODO',
  SET_CHECKED: 'SET_CHECKED',
  REMOVE_ITEM: ' REMOVE_ITEM',
  SET_SELECTED: 'SET_SELECTED',
  DELETE_ALL_SELECTED: 'DELETE_ALL_SELECTED',
  GET_PHOTOS_SUCCESS: 'GET_PHOTOS_SUCCESS',
  GET_PHOTOS_REQUEST: 'PHOTOS_REQUEST',
  GET_PHOTOS_FAILURE: 'PHOTOS_FAILURE',
};
