export const ACTIONS = {
	GET_POSTS_SUCCESS: 'GET_POSTS_SUCCESS',
	GET_POSTS_REQUEST: 'GET_POSTS_REQUEST',
	GET_POSTS_FAILURE: 'GET_POSTS_FAILURE',
	// GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
	// GET_USERS_REQUEST: 'GET_USERS_REQUEST',
	// GET_USERS_FAILURE: 'GET_USERS_FAILURE',
};
